export const GRID_SIZE = 20;
export const CELL_SIZE = 28;
export const PELLETS_TO_ADVANCE = 15;

export const LEVELS = {
  1: {
    name: 'Level 1',
    description: 'Boundary wraps around — avoid yourself',
    color: '#4ade80',
    speed: 160,
    staticObstacles: [],
    movingObstacles: [],
  },
  2: {
    name: 'Level 2',
    description: 'Static obstacles — boundary still wraps',
    color: '#facc15',
    speed: 130,
    staticObstacles: [
      { x: 5, y: 3 },
      { x: 6, y: 3 },
      { x: 7, y: 3 },
      { x: 12, y: 3 },
      { x: 13, y: 3 },
      { x: 14, y: 3 },
      { x: 3, y: 8 },
      { x: 3, y: 9 },
      { x: 3, y: 10 },
      { x: 3, y: 11 },
      { x: 16, y: 8 },
      { x: 16, y: 9 },
      { x: 16, y: 10 },
      { x: 16, y: 11 },
      { x: 8, y: 15 },
      { x: 9, y: 15 },
      { x: 10, y: 15 },
      { x: 11, y: 15 },
      { x: 12, y: 15 },
      { x: 9, y: 7 },
      { x: 10, y: 7 },
      { x: 11, y: 7 },
      { x: 9, y: 13 },
      { x: 10, y: 13 },
      { x: 11, y: 13 },
    ],
    movingObstacles: [],
  },
  3: {
    name: 'Level 3',
    description: 'Moving obstacles join the static ones — stay sharp!',
    color: '#f97316',
    speed: 110,
    staticObstacles: [
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 2, y: 3 },
      { x: 17, y: 2 },
      { x: 16, y: 2 },
      { x: 17, y: 3 },
      { x: 2, y: 17 },
      { x: 3, y: 17 },
      { x: 2, y: 16 },
      { x: 17, y: 17 },
      { x: 16, y: 17 },
      { x: 17, y: 16 },
    ],
    movingObstacles: [
      { x: 5, y: 5, dx: 1, dy: 0 },
      { x: 14, y: 14, dx: -1, dy: 0 },
      { x: 10, y: 3, dx: 0, dy: 1 },
    ],
  },
};
